services:
    PoP\UserRoles\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\UserRoles\Conditional\UserState\TypeResolverDecorators\:
        resource: '../src/Conditional/UserState/TypeResolverDecorators/*'
        public: true

    PoP\UserRoles\Conditional\UserState\DirectiveResolvers\:
        resource: '../src/Conditional/UserState/DirectiveResolvers/*'
        public: true
